id: IA4BC65A0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T05:01:48+00:00'
last_modified: '2022-06-08T12:23:57.664026+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30533
  title: གསུང་འབུམ། བློ་བཟང་བསྟན་པའི་རྒྱལ་མཚན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5AA8:
      image_group_id: I6473
      title: ''
      total_pages: 1258
      order: 1
      base_file: 5AA8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
