id: P009631
initial_creation_type: ocr
source_metadata:
  id: bdr:W30533
  title: གསུང་འབུམ། བློ་བཟང་བསྟན་པའི་རྒྱལ་མཚན
  author: ''
  volumes:
    8f8e3cf864004410a514008e2c667b86:
      image_group_id: I6473
      title: ''
      volume_number: 1
      total_pages: 1258
